CREATE TABLE IF NOT EXISTS wasteProportion (
    `Goal` INT,
    `Target` NUMERIC(2, 1),
    `Indicator` VARCHAR(5) CHARACTER SET utf8,
    `SeriesCode` VARCHAR(12) CHARACTER SET utf8,
    `SeriesDescription` VARCHAR(56) CHARACTER SET utf8,
    `GeoAreaCode` INT,
    `GeoAreaName` VARCHAR(40) CHARACTER SET utf8,
    `Units` VARCHAR(10) CHARACTER SET utf8,
    `Age` VARCHAR(3) CHARACTER SET utf8,
    `Reporting_Type` VARCHAR(1) CHARACTER SET utf8,
    `Column_2000` NUMERIC(4, 2),
    `Column_2001` NUMERIC(4, 2),
    `Column_2002` NUMERIC(4, 2),
    `Column_2003` NUMERIC(4, 2),
    `Column_2004` NUMERIC(4, 2),
    `Column_2005` NUMERIC(4, 2),
    `Column_2006` NUMERIC(4, 2),
    `Column_2007` NUMERIC(4, 2),
    `Column_2008` NUMERIC(4, 2),
    `Column_2009` NUMERIC(4, 2),
    `Column_2010` NUMERIC(4, 2),
    `Column_2011` NUMERIC(4, 2),
    `Column_2012` NUMERIC(4, 2),
    `Column_2013` NUMERIC(4, 2),
    `Column_2014` NUMERIC(4, 2),
    `Column_2015` NUMERIC(4, 2),
    `Column_2016` NUMERIC(4, 2),
    `Column_2017` NUMERIC(3, 2),
    `Column_2018` NUMERIC(4, 2)
);
INSERT INTO wasteProportion VALUES
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',4,'Afghanistan','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,8.6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,9.5,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',8,'Albania','PER_POP_U5','<5Y','G',12.24,NULL,NULL,NULL,NULL,7.32,NULL,NULL,NULL,9.58,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1.58,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',12,'Algeria','PER_POP_U5','<5Y','G',3.1,NULL,9.62,NULL,NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,4.11,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',24,'Angola','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,8.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4.92,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',32,'Argentina','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,1.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',51,'Armenia','PER_POP_U5','<5Y','G',2.53,NULL,NULL,NULL,NULL,5.36,NULL,NULL,NULL,NULL,4.13,NULL,NULL,NULL,NULL,NULL,4.45,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',174,'Comoros','PER_POP_U5','<5Y','G',13.27,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,11.27,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',178,'Congo','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,8.02,NULL,NULL,NULL,NULL,NULL,6.02,NULL,NULL,NULL,8.17,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',188,'Costa Rica','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',36,'Australia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',31,'Azerbaijan','PER_POP_U5','<5Y','G',8.98,3.2,NULL,NULL,NULL,NULL,6.8,NULL,NULL,NULL,NULL,6.6,NULL,3.16,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',50,'Bangladesh','PER_POP_U5','<5Y','G',12.47,12.7,12.4,12.5,14.64,11.8,11.9,17.48,NULL,NULL,NULL,15.68,10.72,NULL,14.38,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',52,'Barbados','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6.77,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',112,'Belarus','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,2.21,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',84,'Belize','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,1.88,NULL,NULL,NULL,NULL,3.29,NULL,NULL,NULL,1.77,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',384,'Côte d''Ivoire','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,9.04,14,NULL,NULL,NULL,NULL,7.61,NULL,NULL,NULL,6.05,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',192,'Cuba','PER_POP_U5','<5Y','G',2.4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',203,'Czechia','PER_POP_U5','<5Y','G',NULL,4.6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',204,'Benin','PER_POP_U5','<5Y','G',NULL,9.04,NULL,NULL,NULL,NULL,8.54,NULL,NULL,NULL,NULL,NULL,NULL,NULL,5.3,NULL,NULL,NULL,5),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',64,'Bhutan','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4.7,NULL,5.85,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',68,'Bolivia (Plurinational State of)','PER_POP_U5','<5Y','G',NULL,NULL,NULL,1.75,NULL,NULL,NULL,NULL,1.41,NULL,NULL,NULL,1.6,NULL,NULL,NULL,1.97,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',458,'Malaysia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,8,11.5,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',462,'Maldives','PER_POP_U5','<5Y','G',NULL,13.4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,10.78,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',466,'Mali','PER_POP_U5','<5Y','G',NULL,12.58,NULL,NULL,NULL,NULL,15.45,NULL,NULL,NULL,9.05,NULL,NULL,NULL,NULL,13.49,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',740,'Suriname','PER_POP_U5','<5Y','G',6.96,NULL,NULL,NULL,NULL,NULL,4.92,NULL,NULL,NULL,5.78,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',760,'Syrian Arab Republic','PER_POP_U5','<5Y','G',4.9,10.3,NULL,NULL,NULL,NULL,10.27,NULL,NULL,11.52,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',70,'Bosnia and Herzegovina','PER_POP_U5','<5Y','G',7.36,NULL,NULL,NULL,NULL,NULL,4.03,NULL,NULL,NULL,NULL,NULL,2.35,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',72,'Botswana','PER_POP_U5','<5Y','G',5.91,NULL,NULL,NULL,NULL,NULL,NULL,7.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',76,'Brazil','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1.83,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',96,'Brunei Darussalam','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2.9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',100,'Bulgaria','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,3.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',854,'Burkina Faso','PER_POP_U5','<5Y','G',NULL,NULL,NULL,21.19,NULL,NULL,24.37,NULL,NULL,11.3,15.54,10.44,10.75,8.1,8.57,NULL,7.53,8.65,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',762,'Tajikistan','PER_POP_U5','<5Y','G',9.4,19.4,6.1,5.9,NULL,8.69,NULL,7.54,NULL,4.3,NULL,NULL,9.9,NULL,NULL,NULL,NULL,5.57,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',764,'Thailand','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,4.73,NULL,NULL,NULL,NULL,NULL,6.71,NULL,NULL,NULL,5.39,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',584,'Marshall Islands','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3.55,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',478,'Mauritania','PER_POP_U5','<5Y','G',15.28,NULL,NULL,NULL,NULL,NULL,NULL,13.61,8.1,NULL,NULL,18.11,11.6,NULL,NULL,14.83,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',108,'Burundi','PER_POP_U5','<5Y','G',9.9,NULL,NULL,NULL,NULL,9,NULL,NULL,NULL,NULL,5.98,NULL,NULL,NULL,NULL,NULL,5.09,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',116,'Cambodia','PER_POP_U5','<5Y','G',17.09,NULL,NULL,NULL,NULL,8.5,NULL,NULL,9.08,NULL,11.03,NULL,NULL,NULL,9.84,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',626,'Timor-Leste','PER_POP_U5','<5Y','G',NULL,NULL,13.7,14.3,NULL,NULL,NULL,24.5,NULL,18.91,NULL,NULL,NULL,10.53,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',768,'Togo','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,16.52,NULL,6,NULL,5.1,NULL,NULL,NULL,6.64,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',484,'Mexico','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,2.02,NULL,NULL,NULL,NULL,NULL,1.6,NULL,NULL,1.03,1.99,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',496,'Mongolia','PER_POP_U5','<5Y','G',7.1,NULL,NULL,NULL,0.6,2.71,NULL,NULL,NULL,NULL,1.86,NULL,NULL,0.99,NULL,NULL,1.27,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',120,'Cameroon','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,6.23,NULL,8.16,NULL,NULL,NULL,NULL,5.72,NULL,NULL,5.22,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',140,'Central African Republic','PER_POP_U5','<5Y','G',10.41,NULL,NULL,NULL,NULL,NULL,12.62,NULL,NULL,NULL,8.3,NULL,7.57,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',499,'Montenegro','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,4.23,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2.8,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',504,'Morocco','PER_POP_U5','<5Y','G',NULL,NULL,NULL,10.77,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2.3,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',508,'Mozambique','PER_POP_U5','<5Y','G',NULL,8.08,NULL,5.42,NULL,NULL,NULL,NULL,4.19,NULL,NULL,6.15,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',776,'Tonga','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,5.2,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',780,'Trinidad and Tobago','PER_POP_U5','<5Y','G',5.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6.4,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',788,'Tunisia','PER_POP_U5','<5Y','G',2.9,NULL,NULL,NULL,NULL,NULL,3.4,NULL,NULL,NULL,NULL,NULL,3.28,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',62,'Central and Southern Asia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,14.13),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',143,'Central Asia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3.58),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',148,'Chad','PER_POP_U5','<5Y','G',13.88,NULL,NULL,NULL,16.17,NULL,NULL,NULL,NULL,NULL,19.38,NULL,NULL,NULL,NULL,13.3,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',792,'Turkey','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,1.05,NULL,NULL,NULL,0.99,NULL,NULL,NULL,NULL,1.85,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',795,'Turkmenistan','PER_POP_U5','<5Y','G',7.1,NULL,NULL,NULL,NULL,NULL,7.21,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4.16,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',798,'Tuvalu','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,3.3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',152,'Chile','PER_POP_U5','<5Y','G',NULL,0.5,0.5,0.5,0.5,NULL,0.5,0.3,0.3,NULL,NULL,NULL,NULL,0.3,0.3,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',156,'China','PER_POP_U5','<5Y','G',2.5,NULL,3,NULL,NULL,2.9,NULL,NULL,2.6,2.6,2.3,NULL,NULL,1.9,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',104,'Myanmar','PER_POP_U5','<5Y','G',10.69,NULL,NULL,10.7,NULL,NULL,NULL,NULL,NULL,7.9,NULL,NULL,NULL,NULL,NULL,NULL,6.63,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',516,'Namibia','PER_POP_U5','<5Y','G',10.04,NULL,NULL,NULL,NULL,NULL,NULL,7.56,NULL,NULL,NULL,NULL,NULL,7.14,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',520,'Nauru','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',524,'Nepal','PER_POP_U5','<5Y','G',NULL,11.32,NULL,NULL,NULL,NULL,12.69,NULL,NULL,NULL,NULL,11.16,NULL,NULL,11.26,NULL,9.64,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',558,'Nicaragua','PER_POP_U5','<5Y','G',NULL,2.32,NULL,NULL,0.3,NULL,1.47,NULL,NULL,NULL,NULL,NULL,2.15,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',800,'Uganda','PER_POP_U5','<5Y','G',4.98,NULL,NULL,NULL,NULL,NULL,6.2,NULL,NULL,NULL,NULL,4.65,4.75,NULL,NULL,NULL,3.47,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',804,'Ukraine','PER_POP_U5','<5Y','G',8.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',834,'United Republic of Tanzania','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,3.55,NULL,NULL,NULL,NULL,2.88,4.88,6.3,NULL,4.54,3.8,4.5,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',408,'Democratic People''s Republic of Korea','PER_POP_U5','<5Y','G',12.2,NULL,8.7,NULL,8.5,NULL,NULL,NULL,NULL,5.2,NULL,NULL,4,NULL,NULL,NULL,NULL,2.5,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',180,'Democratic Republic of the Congo','PER_POP_U5','<5Y','G',NULL,20.9,NULL,NULL,NULL,NULL,NULL,10.36,NULL,NULL,10.65,NULL,NULL,8.13,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',562,'Niger','PER_POP_U5','<5Y','G',16.22,NULL,NULL,NULL,NULL,NULL,12.54,NULL,NULL,NULL,NULL,NULL,18.23,NULL,NULL,NULL,10.11,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',566,'Nigeria','PER_POP_U5','<5Y','G',NULL,NULL,NULL,11.22,NULL,NULL,NULL,13.36,14.47,NULL,NULL,11.58,NULL,18.06,7.9,7.2,10.79,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',840,'United States of America','PER_POP_U5','<5Y','G',NULL,0.4,NULL,NULL,NULL,0.8,NULL,NULL,NULL,0.5,NULL,NULL,0.5,NULL,0.3,NULL,0.4,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',858,'Uruguay','PER_POP_U5','<5Y','G',NULL,NULL,2.4,2.8,3,NULL,NULL,2.5,NULL,NULL,NULL,1.3,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',262,'Djibouti','PER_POP_U5','<5Y','G',NULL,NULL,19.43,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,21.6,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',214,'Dominican Republic','PER_POP_U5','<5Y','G',1.49,NULL,2.24,NULL,NULL,NULL,1.9,2.3,NULL,NULL,NULL,NULL,NULL,2.38,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',807,'North Macedonia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,3.38,NULL,NULL,NULL,NULL,NULL,1.82,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',15,'Northern Africa','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,8.46),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',747,'Northern Africa and Western Asia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6.24),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',753,'Eastern and South-Eastern Asia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4.46),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',30,'Eastern Asia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1.75),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',218,'Ecuador','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,2.03,NULL,2.13,NULL,NULL,NULL,NULL,NULL,2.37,NULL,1.63,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',543,'Oceania (exc. Australia and New Zealand)','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,9.36),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',512,'Oman','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,7.1,NULL,NULL,NULL,NULL,7.5,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',586,'Pakistan','PER_POP_U5','<5Y','G',NULL,14.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,14.8,NULL,10.46,NULL,NULL,NULL,NULL,7.1),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',860,'Uzbekistan','PER_POP_U5','<5Y','G',NULL,NULL,9.02,NULL,NULL,NULL,4.43,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',548,'Vanuatu','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,5.88,NULL,NULL,NULL,NULL,NULL,4.4,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',862,'Venezuela (Bolivarian Republic of)','PER_POP_U5','<5Y','G',3.9,4.4,4.8,5.2,5.2,4.8,4.8,5,4.5,4.1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',591,'Panama','PER_POP_U5','<5Y','G',NULL,NULL,NULL,1.64,NULL,NULL,NULL,NULL,1.25,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',598,'Papua New Guinea','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,4.4,NULL,NULL,NULL,NULL,14.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',600,'Paraguay','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,1.1,NULL,NULL,NULL,NULL,NULL,NULL,2.6,NULL,NULL,NULL,0.96,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',818,'Egypt','PER_POP_U5','<5Y','G',NULL,NULL,NULL,5.24,NULL,5.33,NULL,NULL,7.94,NULL,NULL,NULL,NULL,NULL,9.49,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',222,'El Salvador','PER_POP_U5','<5Y','G',NULL,NULL,NULL,1.31,NULL,NULL,NULL,NULL,1.59,NULL,NULL,NULL,NULL,NULL,2.14,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',704,'Viet Nam','PER_POP_U5','<5Y','G',6.12,NULL,8.9,10.9,11.3,10.7,9.9,10.1,9.7,NULL,7.1,4.39,NULL,6.6,6.8,6.4,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',145,'Western Asia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3.96),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',604,'Peru','PER_POP_U5','<5Y','G',1.14,NULL,NULL,NULL,NULL,1.05,NULL,NULL,0.79,0.6,0.7,0.38,0.65,0.43,0.6,0.62,0.61,0.52,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',608,'Philippines','PER_POP_U5','<5Y','G',NULL,NULL,NULL,6,NULL,NULL,NULL,NULL,6.9,NULL,NULL,7.3,NULL,7.9,NULL,7.1,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',1,'World','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,7.29),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',887,'Yemen','PER_POP_U5','<5Y','G',NULL,NULL,NULL,15.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,13.3,NULL,16.42,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',894,'Zambia','PER_POP_U5','<5Y','G',NULL,NULL,6.21,NULL,NULL,NULL,NULL,5.59,NULL,NULL,NULL,NULL,NULL,6.24,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',226,'Equatorial Guinea','PER_POP_U5','<5Y','G',9.24,NULL,NULL,NULL,2.8,NULL,NULL,NULL,NULL,NULL,NULL,3.1,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',232,'Eritrea','PER_POP_U5','<5Y','G',NULL,NULL,15.02,NULL,NULL,NULL,NULL,NULL,NULL,NULL,15.26,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',748,'Eswatini','PER_POP_U5','<5Y','G',1.69,NULL,NULL,NULL,NULL,NULL,2.89,NULL,1.1,NULL,1.08,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',410,'Republic of Korea','PER_POP_U5','<5Y','G',NULL,NULL,NULL,0.9,NULL,NULL,NULL,NULL,NULL,NULL,1.2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',498,'Republic of Moldova','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,5.9,NULL,NULL,NULL,NULL,NULL,NULL,1.91,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',642,'Romania','PER_POP_U5','<5Y','G',4.3,3.9,3.5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',646,'Rwanda','PER_POP_U5','<5Y','G',8.69,NULL,NULL,NULL,NULL,4.88,NULL,NULL,NULL,NULL,2.91,NULL,NULL,NULL,NULL,1.96,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',662,'Saint Lucia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3.7,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',882,'Samoa','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3.87,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',231,'Ethiopia','PER_POP_U5','<5Y','G',12.36,NULL,NULL,NULL,NULL,12.39,NULL,NULL,NULL,NULL,NULL,9.78,NULL,NULL,8.7,NULL,9.99,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',242,'Fiji','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,6.3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',266,'Gabon','PER_POP_U5','<5Y','G',4.22,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3.45,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',678,'Sao Tome and Principe','PER_POP_U5','<5Y','G',3.93,NULL,NULL,NULL,NULL,NULL,9.6,NULL,11.63,NULL,NULL,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',682,'Saudi Arabia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,11.8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',686,'Senegal','PER_POP_U5','<5Y','G',10.02,NULL,NULL,NULL,NULL,8.67,NULL,NULL,NULL,NULL,NULL,9.81,8.7,9.05,5.88,7.79,7.14,9.01,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',270,'Gambia','PER_POP_U5','<5Y','G',9.11,NULL,NULL,NULL,NULL,NULL,7.37,NULL,NULL,NULL,9.7,NULL,9.56,11.04,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',268,'Georgia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,2.99,NULL,NULL,NULL,1.6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',276,'Germany','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',288,'Ghana','PER_POP_U5','<5Y','G',NULL,NULL,NULL,8.39,NULL,NULL,5.97,NULL,8.72,NULL,NULL,6.93,NULL,NULL,4.7,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',320,'Guatemala','PER_POP_U5','<5Y','G',3.71,NULL,1.93,NULL,NULL,NULL,NULL,NULL,NULL,1.1,NULL,NULL,NULL,NULL,NULL,0.75,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',324,'Guinea','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,10.98,NULL,8.3,NULL,NULL,NULL,5.11,9.97,NULL,NULL,NULL,8.09,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',624,'Guinea-Bissau','PER_POP_U5','<5Y','G',11.78,NULL,NULL,NULL,NULL,NULL,8.81,NULL,NULL,NULL,5.8,NULL,NULL,NULL,5.96,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',328,'Guyana','PER_POP_U5','<5Y','G',12.1,NULL,NULL,NULL,NULL,NULL,8.33,NULL,NULL,5.6,NULL,NULL,NULL,NULL,6.43,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',332,'Haiti','PER_POP_U5','<5Y','G',5.53,NULL,NULL,NULL,NULL,NULL,10.22,NULL,NULL,NULL,NULL,NULL,5.14,NULL,NULL,NULL,NULL,3.72,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',340,'Honduras','PER_POP_U5','<5Y','G',NULL,1.26,NULL,NULL,NULL,NULL,1.36,NULL,NULL,NULL,NULL,NULL,1.37,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',356,'India','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,20.03,NULL,NULL,NULL,NULL,NULL,NULL,NULL,15.1,20.79,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',360,'Indonesia','PER_POP_U5','<5Y','G',5.5,5.4,NULL,NULL,14.4,NULL,NULL,14.8,NULL,NULL,12.3,NULL,NULL,13.5,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',688,'Serbia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,4.5,NULL,NULL,NULL,NULL,3.51,NULL,NULL,NULL,3.9,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',690,'Seychelles','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4.3,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',694,'Sierra Leone','PER_POP_U5','<5Y','G',11.62,NULL,NULL,NULL,NULL,10.17,NULL,NULL,10.48,NULL,10,NULL,NULL,9.46,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',702,'Singapore','PER_POP_U5','<5Y','G',3.6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',90,'Solomon Islands','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4.3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,8.47,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',706,'Somalia','PER_POP_U5','<5Y','G',19.3,NULL,NULL,NULL,NULL,NULL,13.26,NULL,NULL,14.95,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',364,'Iran (Islamic Republic of)','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,4.8,NULL,NULL,NULL,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',368,'Iraq','PER_POP_U5','<5Y','G',6.6,NULL,NULL,5.6,6.9,NULL,5.79,NULL,NULL,NULL,NULL,6.5,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',710,'South Africa','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,7.78,NULL,NULL,NULL,4.79,NULL,NULL,NULL,5.63,NULL,NULL,NULL,2.45,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',728,'South Sudan','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,24.6,NULL,NULL,NULL,24.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',35,'South-Eastern Asia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,8.67),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',388,'Jamaica','PER_POP_U5','<5Y','G',3.03,3.21,2.36,NULL,4.53,NULL,3.69,2.67,2.51,NULL,4.97,NULL,2.96,NULL,3.6,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',392,'Japan','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2.3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',34,'Southern Asia','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,14.6),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',144,'Sri Lanka','PER_POP_U5','<5Y','G',15.5,NULL,NULL,NULL,NULL,NULL,NULL,14.7,NULL,11.8,NULL,NULL,21.4,NULL,NULL,NULL,15.1,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',275,'State of Palestine','PER_POP_U5','<5Y','G',NULL,NULL,9.4,NULL,NULL,NULL,NULL,1.77,NULL,NULL,3.33,NULL,NULL,NULL,1.19,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',400,'Jordan','PER_POP_U5','<5Y','G',NULL,NULL,2.49,NULL,NULL,NULL,NULL,NULL,NULL,1.56,NULL,NULL,2.42,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',398,'Kazakhstan','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,4.88,NULL,NULL,NULL,4.06,NULL,NULL,NULL,NULL,3.1,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',404,'Kenya','PER_POP_U5','<5Y','G',7.39,NULL,NULL,6.23,NULL,6.95,NULL,NULL,NULL,6.94,NULL,NULL,NULL,NULL,4.18,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',414,'Kuwait','PER_POP_U5','<5Y','G',NULL,2.2,2.2,2.6,3.4,3.3,2.8,3.6,2.2,1.8,2.4,1.7,2.4,2.7,2.4,3.1,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',417,'Kyrgyzstan','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,3.36,NULL,NULL,1.3,NULL,NULL,2.85,NULL,2.84,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',432,'Landlocked developing countries (LLDCs)','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6.82),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',418,'Lao People''s Democratic Republic','PER_POP_U5','<5Y','G',17.5,NULL,NULL,NULL,NULL,NULL,7.39,NULL,NULL,NULL,NULL,6.38,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',419,'Latin America and the Caribbean','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1.27),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',199,'Least Developed Countries (LDCs)','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,8.47),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',422,'Lebanon','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,6.6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',426,'Lesotho','PER_POP_U5','<5Y','G',6.82,NULL,NULL,NULL,5.57,NULL,NULL,NULL,NULL,3.81,NULL,NULL,NULL,NULL,2.85,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',430,'Liberia','PER_POP_U5','<5Y','G',7.4,NULL,NULL,NULL,NULL,NULL,NULL,7.88,NULL,NULL,2.8,NULL,NULL,5.63,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',434,'Libya','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,6.5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',450,'Madagascar','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,15.23,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,7.87,NULL,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',454,'Malawi','PER_POP_U5','<5Y','G',6.8,NULL,NULL,NULL,6.3,NULL,4.17,NULL,NULL,1.8,4.06,NULL,NULL,NULL,3.81,2.77,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',716,'Zimbabwe','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,7.26,NULL,NULL,NULL,3.76,3.15,NULL,NULL,NULL,3.36,3.29,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',202,'Sub-Saharan Africa','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6.9),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',729,'Sudan','PER_POP_U5','<5Y','G',NULL,NULL,NULL,NULL,NULL,NULL,14.5,NULL,NULL,NULL,16.31,NULL,NULL,NULL,16.77,NULL,NULL,NULL,NULL),
    (2,2.2,'2.2.2','SH_STA_WASTE','Proportion of children moderately or severely wasted (%)',170,'Colombia','PER_POP_U5','<5Y','G',1.04,NULL,NULL,NULL,NULL,1.58,NULL,NULL,NULL,NULL,0.9,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
